name: Cypress Cloud

on: 
  workflow_dispatch:
    inputs:
      spec: 
        description: Run by cypress command line
        default: cypress/e2e/**

jobs: 
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{github.events.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: 1ed26be2-b8d7-4b88-bb18-8261694726ce
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: chrome
          record: true
          group: UI Chrome
          spec: ${{github.events.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: 1ed26be2-b8d7-4b88-bb18-8261694726ce
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  cypress-e2e-firefox:
    needs: cypress-e2e-chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: firefox
          record: true
          group: UI Firefox
          spec: ${{github.events.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: 1ed26be2-b8d7-4b88-bb18-8261694726ce
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  cypress-e2e-edge:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.5

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: edge
          record: true
          group: UI Edge
          spec: ${{github.events.inputs.spec}}
        env:
          CYPRESS_RECORD_KEY: 1ed26be2-b8d7-4b88-bb18-8261694726ce
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
